### ISSUE TITLE
COLLADASW::StreamWriterException

### ISSUE THREAD

**Issue by simiii** [bimspot/xeokit-converter#2]
Hi,

when I exec -ti into the docker container and execute the following command:
`IfcConvert bascifm.ifc output.dae`
I get the following exception:
```
root@bd9a83e0ff7e:/home# IfcConvert bascifm.ifc output.dae
IfcOpenShell IfcConvert 0.6.0b0 (OCC 7.3.0)
terminate called after throwing an instance of 'COLLADASW::StreamWriterException'
Aborted
```
In the github repository of IfcOpenshell, there seems to be an issue with a file name encoding: https://github.com/IfcOpenShell/IfcOpenShell/issues/797

Any help would be appreciated.

[
bascifm.ifc
](url)

**Comment by simiii** [comment]
This seems to happen if I share the ifc files from my windows host with the docker container.

For the record if anyone else stumbles into the problem I start the container like so:
`docker run --rm -it -v %cd%:/home libal/xeokitconverter`

If I manually create the ifc file in the container everything works fine.

**Comment by eriadam** [comment]
Hello, This probably has to do with how you mount the volume. [Please refer to the docs from Docker.](https://docs.docker.com/engine/reference/commandline/run/#mount-volume--v---read-only)
