### ISSUE TITLE
encountered

### ISSUE THREAD

**Issue by sd63534790** [bimspot/xeokit-converter#8]
root@554c60786a5d:/home/models# IfcConvert -v -y --use-element-guids dxs.ifc scene.dae
IfcOpenShell IfcConvert 0.6.0b0 (OCC 7.3.0)

Log:
[Notice] exclude entities IfcOpeningElement IfcSpace
[Error] Null token encountered, premature end of file?
[Error] No support for file schema encountered ()
[Error] Unable to parse input file 'dxs.ifc'

**Comment by eriadam** [comment]
hello. something seems to be wrong with your IFC file. schema missing?
please report this at the library's repo: https://github.com/IfcOpenShell/IfcOpenShell
